# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('history', '0001_initial'), ('history', '0002_auto_20170928_2001'), ('history', '0003_remove_histentry_orderid'), ('history', '0004_auto_20170929_0327'), ('history', '0005_auto_20170929_0327'), ('history', '0006_histdata'), ('history', '0007_auto_20170929_1616'), ('history', '0008_auto_20170930_0527'), ('history', '0009_auto_20170930_0540'), ('history', '0010_auto_20170930_0545'), ('history', '0011_histentry_paymethod'), ('history', '0012_auto_20170930_0552'), ('history', '0013_auto_20170930_0553'), ('history', '0014_auto_20170930_1628'), ('history', '0015_auto_20171001_1335'), ('history', '0016_auto_20171016_0405')]

    initial = True

    dependencies = [
        ('Catalog', '0009_auto_20170928_2132'),
        ('user', '0008_auto_20170930_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderOwner', models.CharField(max_length=64)),
                ('orderTime', models.DateTimeField(auto_now_add=True, verbose_name='Order Time')),
            ],
        ),
        migrations.CreateModel(
            name='HistData',
            fields=[
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.HistEntry')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('sumPrice', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Total Price')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='After Tax')),
                ('productID', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Catalog.Product', verbose_name='Product')),
                ('EntryId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Entry ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='histentry',
            name='id',
        ),
        migrations.AddField(
            model_name='histentry',
            name='orderId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
        migrations.AddField(
            model_name='histentry',
            name='status',
            field=models.CharField(choices=[('PROCESS', 'Processing'), ('TRANSIT', 'In Transit'), ('RECEIVE', 'Received')], default='PROCESS', max_length=7),
        ),
        migrations.AddField(
            model_name='histentry',
            name='trackingNo',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Tracking No.'),
        ),
        migrations.AddField(
            model_name='histentry',
            name='payMethod',
            field=models.CharField(choices=[('CREDIT', 'Credit Card')], default='CREDIT', max_length=7, verbose_name='Payment Method'),
        ),
        migrations.RemoveField(
            model_name='histentry',
            name='orderOwner',
        ),
        migrations.AddField(
            model_name='histentry',
            name='address',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Address'),
        ),
        migrations.AddField(
            model_name='histentry',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
