# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistData',
            fields=[
                ('entry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Entry ID')),
                ('product_id', models.CharField(default=None, max_length=30, verbose_name='Product')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('sum_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Total Price')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='After Tax')),
            ],
        ),
        migrations.CreateModel(
            name='HistEntry',
            fields=[
                ('order_id', models.UUIDField(default=uuid.UUID('0a3d54cb-fe7f-4e40-ac94-380883c2d867'), editable=False, primary_key=True, serialize=False, verbose_name='Order ID')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='Order Time')),
                ('status', models.CharField(choices=[('PROCESS', 'Processing'), ('TRANSIT', 'In Transit'), ('RECEIVE', 'Received')], default='PROCESS', max_length=7)),
                ('tracking_no', models.CharField(blank=True, default='', max_length=16, verbose_name='Tracking No.')),
                ('pay_method', models.CharField(choices=[('CREDIT', 'Credit Card')], default='CREDIT', max_length=7, verbose_name='Payment Method')),
                ('address', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Address')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.AddField(
            model_name='histdata',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.HistEntry'),
        ),
    ]
