# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_squashed_0016_auto_20171016_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histdata',
            old_name='EntryId',
            new_name='entryId',
        ),
    ]
