# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-29 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='orderId',
            new_name='orderID',
        ),
        migrations.AlterField(
            model_name='order',
            name='shipMethodID',
            field=models.IntegerField(default=0),
        ),
    ]
