# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histentry',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('bb14c72e-c56a-49ab-93ee-bbd5b0eaf480'), editable=False, primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
    ]
