# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histentry',
            name='orderDate',
            field=models.DateField(auto_now_add=True, verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='histentry',
            name='orderID',
            field=models.CharField(max_length=64, verbose_name='Order ID'),
        ),
    ]
