# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histentry',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('81ea4bca-1fd9-4c55-b64b-dd630c3eef4a'), editable=False, primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
    ]
