# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histentry',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('b67cbec3-842b-4255-a631-04133a54bfb4'), editable=False, primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
    ]
