# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='histentry',
            name='shipping_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='histentry',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('708519d3-b491-4237-8459-ff5517022fcd'), editable=False, primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
    ]
