# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20171123_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histentry',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('73bcb94a-9d64-454a-96ec-ad4ffe94441e'), editable=False, primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
    ]
