# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20171124_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histentry',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('ef1ae7dd-9464-4e23-8492-522175fc10b5'), editable=False, primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
    ]
