# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20171016_0412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histdata',
            old_name='productID',
            new_name='productId',
        ),
    ]
