# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-29 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import history.models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20170929_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.DecimalField(decimal_places=0, max_digits=13, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('publisher', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('weight', models.FloatField()),
                ('isMonocrome', models.BooleanField(default=True)),
                ('paperType', models.CharField(choices=[('NS', 'Newsprint'), ('CP', 'Coated Paper'), ('UP', 'Uncoated Paper'), ('BP', 'Bond Paper'), ('GR', 'Green Read Paper')], max_length=2)),
                ('coverType', models.CharField(choices=[('PD', 'Paperback'), ('HC', 'Hardcover')], max_length=2)),
                ('size_height', models.FloatField()),
                ('size_width', models.FloatField()),
                ('size_thickness', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('pictureUrl', models.ImageField(blank=True, null=True, upload_to=history.models.get_product_image_path)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('catagory', models.ManyToManyField(to='history.Catagory')),
            ],
        ),
    ]
