# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20171122_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histdata',
            name='product_id',
            field=models.CharField(default=None, max_length=36, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='histentry',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('ebb03957-cb01-4250-955d-db12def03a88'), editable=False, primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='histentry',
            name='pay_method',
            field=models.CharField(choices=[('CREDIT', 'Credit Card'), ('CASH', 'Cash Transfer')], default='CASH', max_length=7, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='histentry',
            name='status',
            field=models.CharField(choices=[('PROCESS', 'Processing'), ('TRANSIT', 'In Transit'), ('RECEIVE', 'Received'), ('WAITING', 'Waiting for Payment')], default='WAITING', max_length=7),
        ),
    ]
