# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 03:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_remove_histentry_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='histentry',
            name='orderDate',
        ),
        migrations.AddField(
            model_name='histentry',
            name='orderTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 29, 3, 27, 5, 5261), verbose_name='Order Time'),
        ),
    ]
