# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20171016_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histdata',
            name='entryId',
            field=models.UUIDField(default=uuid.UUID('589455e9-5f54-4c2b-a04e-4e4792d65dc0'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Entry ID'),
        ),
    ]
