# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-29 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_catagory_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productID',
            new_name='id',
        ),
    ]
