# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20171123_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histentry',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('2e6a6a77-654c-4616-ab05-f4ad398441da'), editable=False, primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
    ]
