# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20170929_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histentry',
            name='orderTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Order Time'),
        ),
    ]
