# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20171016_0419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histdata',
            old_name='orderId',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='histdata',
            old_name='productId',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='histdata',
            old_name='sumPrice',
            new_name='sum_price',
        ),
        migrations.RenameField(
            model_name='histentry',
            old_name='orderTime',
            new_name='order_time',
        ),
        migrations.RenameField(
            model_name='histentry',
            old_name='payMethod',
            new_name='pay_method',
        ),
        migrations.RenameField(
            model_name='histentry',
            old_name='trackingNo',
            new_name='tracking_no',
        ),
        migrations.RemoveField(
            model_name='histdata',
            name='entryId',
        ),
        migrations.RemoveField(
            model_name='histentry',
            name='orderId',
        ),
        migrations.AddField(
            model_name='histdata',
            name='entry_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Entry ID'),
        ),
        migrations.AddField(
            model_name='histentry',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('326e77bc-576e-47af-8989-6597d6aa35e1'), editable=False, primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
    ]
