# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-29 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20170929_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='userID',
            field=models.IntegerField(default='0'),
        ),
    ]
