# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20171123_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histentry',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('885a20d2-5f56-466f-8ed5-0fe6fca3f72a'), editable=False, primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
    ]
