# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_auto_20171016_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histentry',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('18eb6b83-b1b8-4e5f-a47c-ce539dd1ad02'), editable=False, primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
    ]
