# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_auto_20171124_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histentry',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('f8897bf0-647f-4756-9013-e4b3c3c007b2'), editable=False, primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
    ]
