# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_histdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='histentry',
            name='id',
        ),
        migrations.AddField(
            model_name='histentry',
            name='orderId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
    ]
