# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_auto_20171016_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histentry',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('2e2a593e-11e8-4861-a083-7385b5e7dc5a'), editable=False, primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
    ]
