# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_auto_20171016_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histdata',
            name='product_id',
            field=models.CharField(default=None, max_length=30, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='histentry',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('abb33168-ded5-4ab2-b4cf-5505c78462f9'), editable=False, primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
    ]
