# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_auto_20170930_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='histdata',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='histdata',
            name='sumPrice',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='histdata',
            name='tax',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='histentry',
            name='trackingNo',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Tracking No.'),
        ),
    ]
