# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_auto_20171016_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histentry',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('2f239324-7f4c-4461-b2f1-10b25c25015c'), editable=False, primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
    ]
