# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_auto_20170930_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histdata',
            name='sumPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='histdata',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
