# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_auto_20171016_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histentry',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('1172f3e6-5755-4c5b-b99d-6715245c5cc7'), editable=False, primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
    ]
