# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0010_auto_20170930_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='histentry',
            name='payMethod',
            field=models.CharField(choices=[('CREDIT', 'Credit Card')], default='CREDIT', max_length=7),
        ),
    ]
