# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0011_histentry_paymethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histentry',
            name='payMethod',
            field=models.CharField(choices=[('CREDIT', 'Credit Card')], default='CREDIT', max_length=7, verbose_name='Payment Method'),
        ),
    ]
