# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0012_auto_20170930_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histdata',
            name='orderName',
            field=models.CharField(max_length=300, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='histdata',
            name='sumPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='histdata',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='After Tax'),
        ),
    ]
