# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0015_auto_20171001_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='histdata',
            name='id',
        ),
        migrations.AddField(
            model_name='histdata',
            name='EntryId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Entry ID'),
        ),
        migrations.AlterField(
            model_name='histdata',
            name='productID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Catalog.Product', verbose_name='Product'),
        ),
    ]
