# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isMonocrome',
            field=models.BooleanField(),
        ),
    ]
