# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20170928_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
