# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20170929_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
