# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='token_activate',
            new_name='token',
        ),
    ]
