# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170930_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('AddrID', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('addr', models.CharField(default=None, max_length=512)),
                ('city', models.CharField(default=None, max_length=128)),
                ('zip', models.IntegerField(default=None)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
