# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
