# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20170930_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='address',
            name='userID',
            field=models.IntegerField(default=None),
        ),
    ]
