# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0010_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isMonocrome',
        ),
        migrations.AddField(
            model_name='product',
            name='printingType',
            field=models.CharField(choices=[('MN', 'Monocrome'), ('CL', 'Color')], default='MN', max_length=2),
            preserve_default=False,
        ),
    ]
