# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0011_auto_20171016_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('is_showing', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='1', max_length=1)),
                ('product', models.ManyToManyField(to='Catalog.Product')),
            ],
        ),
    ]
