# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0011_auto_20171014_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='printingType',
            field=models.CharField(choices=[('MN', 'Monocrome'), ('CL', 'Colorized')], max_length=2),
        ),
    ]
