# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0012_indexgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexgroup',
            name='priority',
            field=models.CharField(choices=[('5', '5 (Highest)'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1 (Lowest)')], default='1', max_length=1),
        ),
    ]
